---
- name: configure environment
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/couchbase/vars
    - group_vars/couchbase/secret_vars

  vars: 
    count: '{{ servers - 1 }}' # udf 
    
  tasks: 
  - name: check minumum node size
    fail: 
      msg: "CouchBase Server requires a minumum of 8GB RAM"
    when: (type == 'g6-nanode-1') or 
          (type == 'g6-standard-1') or 
          (type == 'g6-standard-2') or 
          (type == 'g6-dedicated-2') or 
          (type == 'g7-premium-2') | bool

  - name: create couchbase cluster
    linode.cloud.instance: 
      label: '{{ instance_prefix }}-{{ item | int +1 }}-{{ uuid }}'
      api_token: '{{ api_token }}'
      type: '{{ type }}'
      region: '{{ region }}'
      image: '{{ image }}'
      root_pass: '{{ root_pass }}'
      authorized_keys: '{{ ssh_keys }}'
      private_ip: true
      stackscript_id: 1366193
      ua_prefix: 'marketplace-couchbase-occ'
      tags: '{{ cluster_uuid }}'
      state: present
    with_sequence: count='{{ count }}'

  - name: collect cluster details
    linode.cloud.instance_info:
      api_token: '{{ api_token }}'
      label: '{{ instance_prefix }}-{{ item | int }}-{{ uuid }}'
    register: cluster_info
    with_sequence: count='{{ count | int + 1 }}'

  - name: update group_vars with server variables
    blockinfile:
      path: ./group_vars/couchbase/vars
      marker: "# {mark} INSTANCE VARS"
      block: |
        #jinja2: trim_blocks:False
        couchbase_data:
          server:
            {%- for count in range(count | int + 1) %}
            - couchbase-server-{{ count }}:
              instance:
                hostname: {{ cluster_info.results[count].instance.label | replace('_', '-') }}
                ip_pub1: {{ cluster_info.results[count].instance.ipv4[0] }}
                ip_priv1: {{ cluster_info.results[count].instance.ipv4[1] }}
            {%- endfor %}        
         

  - name: test connectivity
    ping: 
    with_items: "{{ item.instance.ipv4[0] }}"
    loop: 
    - "{{ cluster_info.results }}"

  - name: update inventory
    blockinfile:
      path: ./hosts
      marker: "# {mark} COUCHBASE LINODES"
      block: |
        #jinja2: trim_blocks:False
        [couchbase_cluster]
        localhost ansible_connection=local user=root
        {%- for count in range(count | int) %}
        {{ cluster_info.results[count + 1].instance.ipv4[0] }}
        {%- endfor %}

  - name: wait for port 22 to become open
    wait_for:
      port: 22
      host: '{{ item.instance.ipv4[0] }}'
      search_regex: OpenSSH
      delay: 10
    connection: local
    with_items: 
    - "{{ cluster_info.results }}"